<ENV>:
    token_info:
      mil_token_url: <MIL_TOKEN_URL>
      client_id: <MIL_CLIENT_ID>
      client_secret: <MIL_CLIENT_SECRET>
      grant_type: <MIL_GRANT_TYPE>
    tpp:
      tppId: <TPP_ID>
      authenticationType: <AUTHENTICATION_TYPE>
      authenticationUrl: <AUTHENTICATION_URL>
      businessName: <BUSINESS_NAME>
      contact:
        email: <EMAIL>
        name: <NAME>
        number: <NUMBER>
      entityId: <ENTITY_ID>
      idPsp: <ID_PSP>
      legalAddress: <LEGAL_ADDRESS>
      messageUrl: <MESSAGE_URL>
      state: <STATE>
      tokenSectionEncrypted:
        bodyAdditionalProperties:
          client_id: <CLIENT_ID_ENCRYPTED>
          client_secret: <CLIENT_SECRET_ENCRYPTED>
          grant_type: <GRANT_TYPE_ENCRYPTED>
          contentType: <CONTENT_TYPE>
      tokenSectionDecrypted:
        bodyAdditionalProperties:
          client_id: <CLIENT_ID>
          client_secret: <CLIENT_SECRET>
          grant_type: <GRANT_TYPE>
          contentType: <CONTENT_TYPE>
