name: Build and Analyze

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  sonarqube:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage pytest

      - name: Run tests and generate coverage report
        run: |
          coverage run -m pytest
          coverage xml

      - name: Display coverage.xml content (for debugging)
        run: cat coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@bfd4e558cda28cda6b5defafb9232d191be8c203 # v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ vars.SONARCLOUD_PROJECT_KEY }}
            -Dsonar.organization=${{ vars.SONARCLOUD_ORG }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=api,bdd,conf
            -Dsonar.tests=test
            -Dsonar.python.coverage.reportPaths=coverage.xml