name: Build
on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:
  sonarqube:
    name: SonarQube Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade
          pip install -r requirements.txt
      - name: Install tox and any other packages
        run: pip install tox
      - name: Run tox
        run: tox -e py
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run tests and coverage
        run: |
          pytest --cov=. --cov-report=xml

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ vars.SONARCLOUD_PROJECT_KEY }}
            -Dsonar.organization=${{ vars.SONARCLOUD_ORG }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.python.version=3.10
            -Dsonar.sources=.
            -Dsonar.exclusions=**/_pycache_/**,**/.pyc,**/test/**
            -Dsonar.coverageReportPaths=coverage.xml
