name: Build

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  sonarqube:
    name: SonarCloud with Python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests and generate Cobertura coverage report
        run: |
          pytest --cov=. --cov-report=cobertura:coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ vars.SONARCLOUD_PROJECT_KEY }}
            -Dsonar.organization=${{ vars.SONARCLOUD_ORG }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.python.version=3.10
            -Dsonar.sources=.
            -Dsonar.coverageReportPaths=coverage.xml